camunda.client.mode=saas
camunda.client.auth.client-id=i-C6aYth~jb3bZI~q_EoThGwc4OjbCft
camunda.client.auth.client-secret=ozKocpWZ5K7TrfstXUYH1FE16-l6tyGt9eH7PQlwbVLIVCfdgCFX4xTeVs9G1MPT
camunda.client.cloud.cluster-id=4a769a7f-fc41-405b-acca-c4ed8389f102
camunda.client.cloud.region=lhr-1
